#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --distribution bookworm \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --binary-images iso-hybrid \
  --debian-installer false \
  --memtest none \
  --apt-recommends false \
  --mirror-bootstrap "http://deb.debian.org/debian" \
  --mirror-chroot "http://deb.debian.org/debian" \
  --mirror-binary "http://deb.debian.org/debian" \
  --mirror-chroot-security "http://security.debian.org/debian-security" \
  --mirror-binary-security "http://security.debian.org/debian-security" \
  --security false \
  --iso-application "Hydro Desk OS" \
  --iso-publisher "HYDROELECTRICO" \
  --iso-volume "HYDRO_DESK_OS" \
  --bootappend-live "boot=live components username=hydro hostname=hydro-desk locales=en_US.UTF-8 keyboard-layouts=us timezone=UTC quiet splash" \
  "${@}"
